basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path('add/', views.basket_add, name="basket_add"),
    path('delete/', views.basket_delete, name="basket_delete"),
    path('update/', views.basket_update, name="basket_update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    # path('', views.index, name="index"),
    path("", views.all_products, name="all_products"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("shop/<slug:category_slug>", views.category_list, name="category_list"),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User  # User model
from django.db import models
from django.urls import reverse


# Create your models here.
# the ProductManager class is responsible for creating models that are related to the Product models
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    # A slug is a unique identifier for a category that is used in the URL to access a category page.
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="product", on_delete=models.CASCADE
    )
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="product_creator"
    )
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default="admin")
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/", default="images/default.png")
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render, get_object_or_404
from .basket import Basket
from store.models import Product
from django.http import JsonResponse



# Create your views here.
def basket_summary(request):
    basket= Basket(request)
    # print(basket)
    return render(request, 'store/basket/summary.html', {'basket':basket})

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)
        
        basketqty = basket.__len__()
        response = JsonResponse({'qty':basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'subtotal':baskettotal, 'qty':basketqty})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty':basketqty, 'subtotal':baskettotal})
        return response     


        

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# def index(request):
#     return render(request, "store/cover.html")


def all_products(request):
    # products = Product.objects.filter(is_active=True)
    products = Product.products.all()
    context = {"products": products}
    return render(request, "store/home.html", context)


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {"category": category, "products": products}
    return render(request, "store/products/category.html", context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    context = {"product": product}
    return render(request, "store/products/product_detail.html", context)

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}MyBookStore{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
      integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">Bookstore</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
        
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Library</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url "store:all_products" %}">All</a></li>
                      {% for c in categories %}
                      <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{c.name|title }}</a></li>
                      {% endfor %}
                    </ul>
                  </li>
                </ul>
                <a type="button" role="button" href="{% url 'basket:basket_summary' %}" class="btn btn-btn-outline-secondary" >

                  {% with total_qty=basket|length %}
                    <div id="basket-qty" class="d-inline-flex">
                      {% if total_qty > 0 %}
                        {{total_qty}}
                      {% else %}
                        0
                      {% endif %}
                    </div>
                  {% endwith %}

                
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                Basket
              </a>
              </div>
              
            </div>
          </nav>
      </header>

    <div id="content">{% block content %}{% endblock %}</div>

    <div class="container">
      <footer class="py-5">
        <div class="row">
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-6 col-md-2 mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
              <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
            </ul>
          </div>
    
          <div class="col-md-5 offset-md-1 mb-3">
            <form>
              <h5>Subscribe to our newsletter</h5>
              <p>Monthly digest of what's new and exciting from us.</p>
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                <label for="newsletter1" class="visually-hidden">Email address</label>
                <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                <button class="btn btn-primary" type="button">Subscribe</button>
              </div>
            </form>
          </div>
        </div>
    
        <div class="d-flex flex-column flex-sm-row justify-content-between py-3 my-3 border-top">
          <p>&copy; 2022 CreativeCraft, Inc. All rights reserved.</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </div>
      </footer>
    </div>
    
  </body>
</html>

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
    Basket Summary
{% endblock %}

{% block content %}
    <main>
        <div class="container">
            <h1 class="h5">Shopping Basket</h1>
            {% for item in basket %}
            {% with product=item.product %}
            <div data-index="{{product.id}}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}" />
                </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset"><h1 class="h5 pt-2">{{product.title}}</h1></a>
            
            <div class="border">
                <div class="col border-bottom">
                    <div class="row p-3">
                        <div class="col-6">Hardback Book</div>
                        <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price}}</span></div>
                    </div>
                </div>
                <div class="col">
                    <div class="row p-3">
                        <div class="col-12">
                        <label for="select">Qty</label>
                        <select id="select{{product.id}}">
                            <option selected>
                                {{item.qty}}
                            </option>
                            <option value="">1</option>
                            <option value="">2</option>
                            <option value="">3</option>
                            <option value="">4</option>
                        </select>
                        <button type="button" id="update-button" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm update-button">
                            Update
                        </button>
                        <button type="button" id="delete-button" data-index="{{product.id}}" class="btn btn-outline-danger btn-sm delete-button">
                            Delete
                        </button>

                    </div>
                    </div>
                    </div>
                </div>
            </div>
            </div>
            {% endwith %}
            {% endfor %}
            <div class="col-12 text-end">
            <div class="h6 bfw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div>
            </div>
            </div>
        </div>

</main>
<script>
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var prodid = $(this).data('index');
            $.ajax({
                type: 'POST',
                url:'{% url "basket:basket_delete" %}',
                data: {
                    productid: $(this).data('index'),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action:'post'
                },
                success: function(json){
                    console.log(prodid)
                    $('.product-item[data-index="'+ prodid +'"]').remove();
                    document.getElementById("basket-qty").innerHTML = json.qty
                    document.getElementById("subtotal").innerHTML = json.subtotal
                },
                error:function(xhr, errmsg, err){},
            });
        })



        //Update item
        $(document).on('click', '.update-button', function (e) {
            e.preventDefault();
            var prodid = $(this).data('index');
            $.ajax({
                type: 'POST',
                url:'{% url "basket:basket_update" %}',
                data: {
                    productid: $(this).data('index'),
                    productqty: $('#select'+ prodid +' option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action:'post'
                },
                success: function(json){
                    document.getElementById("basket-qty").innerHTML = json.qty
                    document.getElementById("subtotal").innerHTML = json.subtotal
                    
                },
                error:function(xhr, errmsg, err){}
            });
        })
    </script>
{% endblock %}

templates/store/home.html
{% extends "./base.html" %}

{% load static %}

{% block title %}BookStore{% endblock %}

{% block content %}
<main>

    <section class="py-5 text-center container">
      <div class="row py-lg-2">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="h1 fw-bold">Search, Read, Buy, Review </h1>
          <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Make an account </a>
          </p>
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="pb-4 h5">All Books</div>
        <div class="row row-cols-1 row-cols-sm-3 row-cols-md-4 g-4">

            {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">
                    <a href="{{ product.get_absolute_url }}""><img class="card-img-top" alt="Responsive image" src="{{ product.image.url }}"></a>
        
                    <div class="card-body">
                        <p class="card-text">
                            {{ product.title }}
                        </p>
                        {% if product.price == 0 %}
                        <p class="card-text"><i>free</i></p>
                        {% else %}
                        <p class="card-text">
                            <small class="text-muted"><i>$ {{ product.price }}</i></small>
                        </p>
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">View</a></button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">{{product.created|timesince}}</small>
                        </div>
                    </div>
                    </div>
                </div>

            {% endfor %}

        </div>

      </div>
    </div>
    <div class="container px-4 py-5" id="custom-cards">
      <h2 class="pb-2 border-bottom">Custom cards</h2>
  
      <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
        <div class="col">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Short title, long jacket</h2>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                  <small>Earth</small>
                </li>
                <li class="d-flex align-items-center">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                  <small>3d</small>
                </li>
              </ul>
            </div>
          </div>
        </div>
  
        <div class="col">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-2.jpg');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Much longer title that wraps to multiple lines</h2>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                  <small>Pakistan</small>
                </li>
                <li class="d-flex align-items-center">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                  <small>4d</small>
                </li>
              </ul>
            </div>
          </div>
        </div>
  
        <div class="col">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-3.jpg');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
              <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Another longer title belongs here</h2>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                  <small>California</small>
                </li>
                <li class="d-flex align-items-center">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                  <small>5d</small>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <div class="b-example-divider"></div>
  
    <div class="container px-4 py-5" id="icon-grid">
      <h2 class="pb-2 border-bottom">Icon grid</h2>
  
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#cpu-fill"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#home"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#speedometer2"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#toggles2"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#geo-fill"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#tools"/></svg>
          <div>
            <h4 class="fw-bold mb-0">Featured title</h4>
            <p>Paragraph of text beneath the heading to explain the heading.</p>
          </div>
        </div>
      </div>
    </div>
  
  </main>
{% endblock %}

templates/store/products/category.html
{% extends "../base.html" %}

{% load static %}

{% block title %}
{% if category %} {{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
<main>

    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="pb-3 h5"><h1>{{category.name}}</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">
                    <img class="card-img-top" alt="Responsive image" src="{{ product.image.url }}" width="50%" height="400vw" object-fit="cover">
        
                    <div class="card-body">
                        <p class="card-text">
                            <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                        </p>
                        <p class="card-text">
                            <small class="text-muted">$ {{ product.price }}</small>
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">{{product.created|timesince}}</small>
                        </div>
                    </div>
                    </div>
                </div>

            {% endfor %}

        </div>

      </div>
    </div>
  
  </main>
{% endblock %}

templates/store/products/product_detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="container">
    <main class="pt-5">
       
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{product.title}}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">$ {{ product.price }}</span></div>
                        </div>    
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                            </div>
                            <div class="col-6  text-end"><button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to Cart</button></div>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>


<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url:'{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action:'post'
            },
            success: function(json){
{% comment %} the document.getElementById is used to retrieve the JSON data from the server and return it as a string. {% endcomment %}
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error:function(xhr, errmsg, err){},
        });
    })
</script>


{% endblock %}